name: mukkip
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  # 위치 서비스
  location: ^5.0.3
  geolocator: ^9.0.2
  # 상태 관리
  provider: ^6.0.0
  # HTTP 요청
  http: ^1.1.0
  # 권한 관리
  permission_handler: ^11.0.0
  # 하단 시트
  sliding_up_panel: ^2.0.0+1
  # 이미지 처리
  cached_network_image: ^3.3.0
  # 지도 클러스터링 - 다른 패키지 사용
  maps_toolkit: ^2.0.1
  flutter_naver_map: ^1.3.1
  dio: ^5.4.0
  lottie: ^2.6.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/markers/
    - assets/images/
